version: '2'
services:

  mysql:
    image: mysql:5.7.18
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: heads
      MYSQL_ROOT_PASSWORD: secret


  php:
    container_name: php
    build:
        context: ./
        dockerfile: Dockerfile
    volumes:
      - .:/var/www/heads
    entrypoint:
      - php-fpm


  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes_from:
      - php
    volumes:
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    ports:
      - 8080:80